CREATE TABLE ENDERECO
(
    ID VARCHAR(36) ,
    LOGRADOURO VARCHAR(80) ,
    NUMERO_RESIDENCIAL VARCHAR(10) ,
    COMPLEMENTO VARCHAR(50) ,
    BAIRRO VARCHAR(50) ,
    CIDADE VARCHAR(50) ,
    CEP VARCHAR(8) ,
    UF VARCHAR(2) ,

    PRIMARY KEY (ID)
);

CREATE TABLE USUARIO
(
    ID VARCHAR(36) NOT NULL,
    IDENTIFICACAO VARCHAR(10) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) ,
    SENHA VARCHAR(8) ,
    TIPO_USUARIO VARCHAR(7) NOT NULL,
    ENDERECO_FK VARCHAR(36),
    EMPRESA_FK VARCHAR(36) NOT NULL,

    PRIMARY KEY(ID),
    FOREIGN KEY (ENDERECO_FK) REFERENCES ENDERECO (ID)
);

CREATE TABLE EMPRESA
(
    ID VARCHAR(36) NOT NULL,
    NOME_FANTASIA VARCHAR(100) NOT NULL,
    RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(50) ,
    TELEFONE VARCHAR(13) ,
    ENDERECO_FK VARCHAR(36),

    PRIMARY KEY(ID),
    FOREIGN KEY (ENDERECO_FK) REFERENCES ENDERECO (ID)
);

CREATE TABLE ARQUIVO_BOLETO
(
    ID VARCHAR(36) ,
    NOME VARCHAR(100) ,
    DIRETORIO_LOGO VARCHAR(50) ,
    FILTRO VARCHAR(50) ,
    LAYOUT VARCHAR(50) ,
    MOSTRAR_PREVIEW VARCHAR(50) ,
    MOSTRAR_PROGRESSO VARCHAR(50) ,
    MOSTRAR_SETUP VARCHAR(50) ,
    NUMERO_COPIAS VARCHAR(50) ,
    PRINTER_NOME VARCHAR(100) ,
    SOFTWARE_HOUSE VARCHAR(100) ,
    ALTERAR_ESCALA VARCHAR(50) ,
    NOVA_ESCALA VARCHAR(50) ,
    CALC_NOME_ARQ_PDF_IND VARCHAR(50) ,
    MARGEM_SUP VARCHAR(50) ,
    MARGEM_INF VARCHAR(50) ,
    MARGEM_ESQ VARCHAR(50) ,
    MARGEM_DIR VARCHAR(50) ,

    PRIMARY KEY (ID)
);

CREATE TABLE BANCO
(
    ID VARCHAR(36) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    AGENCIA VARCHAR(5) NOT NULL,
    AGENCIA_DIGITO VARCHAR(5) ,
    CONTA VARCHAR(9) NOT NULL,
    CONTA_DIGITO VARCHAR(9) NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE BOLETO
(
    ID VARCHAR(36) NOT NULL,
    BANCO_FK VARCHAR(36) NOT NULL,
    VALOR VARCHAR(20) NOT NULL,
    DATA_EMISSAO DATE NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    TOTAL_PARCELAS VARCHAR(2) NOT NULL,
    CONVENIO VARCHAR(2) ,
    CODIGO_CEDENTE VARCHAR(2) ,
    CODIGO_TRANSMISSAO VARCHAR(2) ,
    MODALIDADE VARCHAR(2) ,
    RESPONSAVEL_EMISSAO VARCHAR(2) ,
    TIPO_CARTEIRA VARCHAR(2) ,
    TIPO_DOCUMENTO VARCHAR(2) ,
    USUARIO_FK VARCHAR(36) ,
    CARACTERISTICA_TITULO VARCHAR(2) ,
    CODIGO_NEGATIVACAO VARCHAR(2) ,
    EMPRESA_FK VARCHAR(36) ,
    IDENTIFICACAO_DISTRIBUICAO VARCHAR(2) ,
    OPERACAO VARCHAR(30) ,
    CHAVE_PIX VARCHAR(100) ,
    TIPO_CHAVE_PIX VARCHAR(2) ,
    STATUS VARCHAR(20) NOT NULL,
    URL VARCHAR(255) NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (BANCO_FK) REFERENCES BANCO (ID),
    FOREIGN KEY (USUARIO_FK) REFERENCES USUARIO (ID),
    FOREIGN KEY (EMPRESA_FK) REFERENCES EMPRESA (ID)
);

CREATE TABLE CONFIGURACAO_BANCO
(
    ID VARCHAR(36) ,
    TIPO_COBRANCA VARCHAR(2) ,
    NUMERO_CORRESPONDENTE VARCHAR(2) ,
    LAYOUT_VERSAO_ARQUIVO VARCHAR(4) ,
    LAYOUT_VERSAO_LOTE VARCHAR(4) ,
    LOCAL_PAGAMENTO VARCHAR(50) ,
    ORIENTACAO_BANCO VARCHAR(100) ,
    DIGITO VARCHAR(4) ,
    CASAS_DECIMAIS_MORA_JUROS VARCHAR(2) ,
    CIP VARCHAR(50) ,

    PRIMARY KEY (ID)
);

CREATE TABLE CREDENCIAL_BOLETO
(
    ID VARCHAR(36) ,
    CLIENT_ID VARCHAR(20) ,
    CLIENT_SECRET VARCHAR(20) ,
    SCOPE VARCHAR(50) ,
    INDICADOR_PIX VARCHAR(2) ,

    PRIMARY KEY (ID)
);

CREATE TABLE DIRETORIO_BOLETO
(
    ID VARCHAR(36) ,
    LAYOUT_REMESSA VARCHAR(2) ,
    DIRETORIO_ARQUIVO_REMESSA VARCHAR(50) ,
    DIRETORIO_ARQUIVO_RETORNO VARCHAR(50) ,
    NOME_ARQUIVO_REMESSA VARCHAR(100) ,
    NOME_ARQUIVO_RETORNO VARCHAR(100) ,
    NUMERO_ARQUIVO VARCHAR(2) ,
    DATA_ARQUIVO DATE ,
    DATA_CREDITO_LANCAMENTO DATE ,
    IMPRIMIR_MARGEM_PADRAO VARCHAR(2) ,
    LECEDENTE_RETORNO VARCHAR(2) ,
    REMOVE_ACENTOS_ARQUIVO_REMESSA VARCHAR(2) ,
    PREFIXO_ARQUIVO_REMESSA VARCHAR(15) ,

    PRIMARY KEY (ID)
);

CREATE TABLE WEB_SERVICE_BOLETO
(
    ID VARCHAR(36) ,
    PATH_GRAVAR_REGISTRO VARCHAR(50) ,
    AMBIENTE VARCHAR(2) ,
    OPERACAO VARCHAR(2) ,
    VERSAO_DF VARCHAR(4) ,
    USER_CERTIFICATE_HTTP VARCHAR(2) ,
    SSL_TYPE VARCHAR(2) ,
    TIMEOUT VARCHAR(4) ,
    ARQUIVO_CRT VARCHAR(50) ,
    ARQUIVO_KEY VARCHAR(50) ,
    LOG_NIVEL VARCHAR(2) ,
    CAMINHO_GRAVAR_REGISTRO VARCHAR(50) ,
    NOME_ARQUIVO_LOG VARCHAR(100) ,

    PRIMARY KEY (ID)
);

CREATE TABLE CONTA_BANCARIA
(
    ID VARCHAR(36) ,
    NUMERO_CONTA VARCHAR(20) ,
    AGENCIA VARCHAR(10) ,
    BANCO_FK VARCHAR(50) ,
    TIPO_CONTA VARCHAR(20) ,
    TITULAR VARCHAR(36) ,
    DATA_ABERTURA TIMESTAMP ,
    TELEFONE_CONTATO VARCHAR(13) ,
    EMAIL_TITULAR VARCHAR (50),
    CPF_CNPJ VARCHAR(14) ,
    CODIGO_IBAN VARCHAR(29) ,

    PRIMARY KEY (ID),
    FOREIGN KEY (BANCO_FK) REFERENCES BANCO(ID)
);

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_EMPRESA
FOREIGN KEY (EMPRESA_FK) REFERENCES EMPRESA (ID);







