CREATE TABLE USUARIO
(
    ID   VARCHAR(36) PRIMARY KEY,
    IDENTIFICACAO VARCHAR(10),
    NOME VARCHAR(100),
    EMAIL VARCHAR(50)

);

CREATE TABLE EMPRESA
(
  ID VARCHAR(36) PRIMARY KEY,
  nome_fantasia VARCHAR(255) NOT NULL,
  razao_social VARCHAR(255) NOT NULL,
  cnpj VARCHAR(255) NOT NULL,
  telefone VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL
);
